---
namespace: odem
name: optimize
version: 0.3.1
readme: README.md
authors:
  - foo <bar@baz.com>
description: System-level performance and console optimizations
license:
  - GPL-3.0-or-later
tags:
  - linux
  - optimize
  - performance
  - zram
  - tmpfs
  - console
  - odem
repository: https://github.com/my-perfect-system/odem-optimize
documentation: https://github.com/my-perfect-system/odem-optimize
homepage: https://github.com/my-perfect-system/odem-optimize
issues: https://github.com/my-perfect-system/odem-optimize/issues
build_ignore:
  .ansible-lint
  .yamllint
  - .git
  - .github
  - .gitignore
  - "*.tar.gz"
  - .ansible
dependencies:
  odem.base: ">=0.1.0"
  ansible.posix: ">=1.0.0"
