---
- name: Install zram packages
  ansible.builtin.apt:
    name: "{{ zram_packages }}"
    state: present
    update_cache: true
  become: true

- name: Configure zram swap device
  ansible.builtin.blockinfile:
    path: "{{ zram_config_path }}"
    marker: "# {mark} ANSIBLE MANAGED: zramswap config"
    block: "ALGO={{ zram_algo }}\nPERCENT={{ zram_percentage }}"
    insertafter: EOF
  become: true

- name: Restart zram service
  ansible.builtin.systemd:
    name: "{{ zram_service }}"
    state: restarted
    daemon_reload: true
  become: true
