---
- name: Install kmscon packages
  ansible.builtin.package:
    name: "{{ kmscon_packages }}"
    state: present
    update_cache: true
  become: true

- name: Ensure kmscon config directory exists
  ansible.builtin.file:
    path: "{{ kmscon_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Deploy kmscon configuration file
  ansible.builtin.copy:
    src: "{{ kmscon_conf_src }}"
    dest: "{{ kmscon_conf_dst }}"
    owner: root
    group: root
    mode: "0644"
  become: true
