---
- name: "OPTIMIZE_KMSCON - Install kmscon packages"
  ansible.builtin.apt:
    name: "{{ kmscon_packages }}"
    state: present
    default_release: "{{ kmscon_default_release }}"
    update_cache: true
  become: true

- name: "OPTIMIZE_KMSCON - Ensure kmscon_config_dir exists"
  ansible.builtin.file:
    path: "{{ kmscon_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "OPTIMIZE_KMSCON - Deploy kmscon.conf"
  ansible.builtin.copy:
    src: "{{ kmscon_conf_src }}"
    dest: "{{ kmscon_conf_dst }}"
    owner: root
    group: root
    mode: "0644"
  become: true
