---
- name: "OPTIMIZE_RAMDISKS_MAIN - Compute mount state"
  ansible.builtin.include_tasks: compute.yml

- name: "OPTIMIZE_RAMDISKS_MAIN - Convert ramdisks_mount to tmpfs with backup/restore"
  ansible.builtin.include_tasks: convert.yml